version: '3'

services:
  n8n-mcp:
    build:
      context: ./n8n-mcp
    container_name: n8n-mcp
    restart: always
    environment:
      - TRANSPORT=http
      - PORT=3000
      - N8N_URL=http://n8n:5678
    networks:
      - app-network

networks:
  app-network:
    external: true
